### ISSUE TITLE
Календарь

### ISSUE THREAD

**Issue by vehsamrak** [MagicGreenHat/Kingdom#38]
В игре день сменяется ночью, и на этом сходства с григорианским календарем заканчиваются. В игровом календаре другое количество сезонов, месяцев и дней в месяце. Один игровой день равен реальному часу.

День - число
Месяц - слово или словосочетание в родительном падеже
Год - число
Сезон - слово или словосочетание в родительном падеже

Примерно дата должна выглядеть как: 13 день волков 115 года (сезон охоты)

Нужен сервис (класс), который будет уметь:
- хранить в себе реальную дату начала отсчета
- хранить в себе список названий месяцев и их порядок, количество дней в каждом месяце (может быть разным)
- хранить в себе список сезонов и входящих в них месяцев
- рассчитывать текущую игровую дату на основе реальной

Данные не должны храниться в БД - а только в самом классе календаря.
Файл класса должен находитьс в директории Rottenwood/KingdomBundle/Service
Класс должен быть назначен как сервис в файле Rottenwood/KingdomBundle/Resources/config/services.yml (по аналогии с kingdom.user_service)

**Comment by vehsamrak** [comment]
Класс, в котором описаны названия игровых месяцев и сезонов
Сделать этот класс симфони-сервисом
Метод сервиса возвращающий текущую игровую дату
Метод возвращающий количество игровых дней с даты начала отсчета
Метод возвращающий количество игровых месяцев с даты начала отсчета
Метод возвращающий количество игровых лет с даты начала отсчета

**Comment by vehsamrak** [comment]
Предлагаю сезоны: охоты, войны, мира, ремесла. Впоследствии можем привязать к сезонам те или иные плюсы к определенным занятиям

**Comment by samizdam** [comment]
Раз число дней не привязано к солярному / лунному циклу, то к чему месяцы? 
Предлагаю делить год на хексы. 
Год из 256 дней: 16 хексов по 16 дней.

**Comment by samizdam** [comment]
Или хексецы =)

**Comment by samizdam** [comment]
События последнего хексеца... Как, звучит?

**Comment by samizdam** [comment]
А главное такой календарь графически будет идельно правильно рисоваться.

**Comment by vehsamrak** [comment]
@samizdam идея определенно интересная!

**Comment by samizdam** [comment]
@Rottenwood я тут всерьёз задумался над реализацией этой фичи, удовлетворяющей всем упомянутым требованиям. Пока не уверен что пришёл к окончательному интерфейсу, публиковать не буду. Но идеи есть.

**Comment by samizdam** [comment]
Полагаю что реальную дату начала отсчета удобнее задавать как timstamp, а не реальную дату - будь то объект или строка. 
Ну и для расчётов брать текущий timestamp. 
Имхо это проще в использовании и реализации.

**Comment by vehsamrak** [comment]
@samizdam Учитывая что о реальной дате никто кроме сервиса в явном виде знать не будет и изменение этой даты "начала времен" не предполагается, это хорошая идея использовать таймстемп юникс эпохи - так можно будет при необходимости рассчитать с помощью сервиса календаря определенный момент в прошлом (например в описании квестов)

**Comment by samizdam** [comment]
_Хм. Попробовал через почту ответить в топик, видимо что-то не так сделал... Ладно, повторюсь._
Да, я примерно так и проектирую реализацию.
Т.о., всего при инициализации можно будет указать следующие параметры: timestamp нулевого игрового дня и scale - отношение игрового времени к реальному. Соответсвенно манипулируя начальным timestamp, можно будет построить календарь «имеющий» прошедшие игровые даты на текущий момент.

Так же для конфигурирования доступны будут кол-во и название месяцев, кол-во дней для каждого.
Ещё сезоны надо добавить. Вообще думаю группировку месяцев в сезоны, как и недели (декады etc) сделать опциональными фичами.
В минимальную конфигурацию будут входить только месяцы и масштаб для расчёта.

**Comment by samizdam** [comment]
https://github.com/FreeElephants/AltEra
