### ISSUE TITLE
Отключить логирование в тестовом окружении

### ISSUE THREAD

**Issue by vehsamrak** [MagicGreenHat/Kingdom#79]

**Comment by samizdam** [comment]
Триколор: 
![russian-issue](https://cloud.githubusercontent.com/assets/1556299/11919817/7dfb7a4c-a76d-11e5-8b4d-65bea93e3c73.png)

Что, где, когда? 
Путём конфигурирования симфонийского?

**Comment by vehsamrak** [comment]
@samizdam почему-то я не ввел описание задачи, из-за этого уже не помню что имелось ввиду :) Пока не вспомнил - закрываю
