### ISSUE TITLE
Переход на php7

### ISSUE THREAD

**Issue by vehsamrak** [MagicGreenHat/Kingdom#82]
Нужно перевести инфраструктуру на php7

**Comment by samizdam** [comment]
Хм, а все ли потенциально необходимые проекту вендоры поддерживают php7?

**Comment by vehsamrak** [comment]
@samizdam Я сделал версию контейнера для php7 и в ней удалось установить почти все что используется в проекте, но есть и проблемы, решением которых сейчас занят:
1. библитека phpredis. У них есть ветка с семеркой с невалящимися тестами, сбилдил либу из исходников
2. codeception. При фаталах иногда не валит тесты! =)

Остальные либы работают.

**Comment by samizdam** [comment]
@Rottenwood, а разве в семёрке оставили фаталы? Я очень надеялся что одной из киллер-фич будет отказ от фатальных ошибок, т.к. это одна из концептуальных проблем в дизайне языка. Например проблема "рождён чтобы умирать" и нестабильность демонов растут из этой особенности.

**Comment by vehsamrak** [comment]
@samizdam возможно. Там действительно был не фатал а другой тип ошибки. Возможно этим и вызвано такое поведение codeception

**Comment by samizdam** [comment]
Да, погуглил, нашёл есть на русском ликбез http://habrahabr.ru/post/261451/ 
Вероятно в эту сторону надо копать.

**Comment by vehsamrak** [comment]
@samizdam в codeception тоже есть ветка php7, можно в композере к ней подвязаться

**Comment by vehsamrak** [comment]
@samizdam проблема есть еще с docblock в шторме (10 версия, с поддержкой пхп7). Не умеет он пока правильно парсить скалярный тайпхинтинг - ругается что тип неверный

**Comment by samizdam** [comment]
@Rottenwood, Eclipse не ругается на скалярный хинт. 
Eclipse вообще почти ни на что не ругается в php =) 
Он и 7-ую версию, формально не поддерживает, как бе.

**Comment by vehsamrak** [comment]
@samizdam шторм 10 поддерживает семерку, якобы. По факту - проблема с аннотациями докблоков. Ругается на новый тайпхинт, говорит неверная аннотация, а исправить не может. Пришлось отключить анализ аннотаций - надеюсь что временно
